name: Django CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4

    steps:
    - name: Install Dependencies
      run: |
        python3 -m venv ./venv
        source venv/bin/active
        pip install -r requirements.txt
